config/routes.rb
GroceryList::Application.routes.draw do
  root 'groceries#index'

  resources :groceries

end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
 
 def index
    @groceries = Grocery.all
  end

  def show
 		@grocery = Grocery.find(params[:id])
	end

	def new
  @grocery = Grocery.new
	end

	def create
	 @grocery = Grocery.create grocery_params
	 redirect_to grocery_path(@grocery)
	end

	def edit
	  @grocery = Grocery.find(params[:id])
	end

def update
    @grocery = Grocery.find(params[:id])
    @grocery.update grocery_params
    redirect_to grocery_path(@grocery)
end

	def destroy
    Grocery.find(params[:id]).destroy
    redirect_to root_path
end

	private
    def grocery_params
      params.require(:grocery).permit(:item, :details)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/views/groceries/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">GroceryList</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="/">My List</a>
        </li>
        <li><a href="/groceries/new">New Item</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/groceries/edit.html.erb
<h1>Edit your item:</h1></br>
<%= form_for @grocery do |f| %>

 <I><%= label_tag(:item, "Item:") %></I>
  <%= f.text_field :item , :class => "form-control" %></br>

  <I><%= label_tag(:details, "Details:") %></I>
  <%= f.text_area :details , :class => "form-control" %></br>

  <%= f.submit "Update", :class => "btn btn-primary btn-default" %>
<% end %>

app/views/groceries/index.html.erb
<%#= link_to "New Item", new_grocery_path, :class => "btn btn-success" %>
<ul>
	<% @groceries.each do |grocery| %>
	  <li>
	  	<%=link_to grocery.item, grocery_path(grocery.id), :class => "item col-lg-4" %>
	    <%= link_to "edit", edit_grocery_path(grocery[:id]), :class => "btn btn-primary btn-xs" %>
	    <%= link_to "delete", grocery, method: :delete, data: { confirm: "Are you sure? No turning back!"}, :class => "btn btn-primary btn-xs" %>
	  </li>
	<% end %>
</ul>

app/views/groceries/new.html.erb
<h1>Add an item to your GroceryList:</h1></br>
<I><%= form_for @grocery do |f| %>

  <%= label_tag(:item, "Item:") %></I>
  <%= f.text_field :item , :class => "form-control" %></br>

  <I><%= label_tag(:details, "Details:") %> </I>
  <%= f.text_area :details, :class => "form-control" %></br>
  <%= f.submit "Create", :class => "btn btn-primary btn-default" %>
<% end %>

app/views/groceries/show.html.erb
</br></br>
<p>Item: <%= @grocery.item%></p>
<p>Details: <%= @grocery.details%></p>

<I><%= link_to "Back To Grocery List",groceries_path%></I>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>GroceryList</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="row" id="main">
			<%= render "header" %>
		  <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1"></div>
		  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="content">
				<%= yield %>
			</div>
	 	  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></div>
	 	</div>
	</body>
</html>